# Generated by Django 5.0.3 on 2024-03-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemissue',
            old_name='date_returned',
            new_name='date_return',
        ),
    ]
