# Generated by Django 5.0.3 on 2024-03-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_date_returned_itemissue_date_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='initial_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
