# Generated by Django 5.0.3 on 2024-03-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_initial_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='initial_amount',
            new_name='original_amount',
        ),
    ]
