# Generated by Django 5.0.3 on 2024-03-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_itemissue_is_returned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockitem',
            name='original_value',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
